#!/bin/sh
# [This file came with the gocollect-osso package]

CYAN=$(printf '\033[1;36m')
GREEN=$(printf '\033[1;32m')
NONE=$(printf '\033[0m')
RED=$(printf '\033[1;31m')
WHITE=$(printf '\033[1m')
YELLOW=$(printf '\033[1;33m')

# value=$(gocollect -sk core.meta 2>/dev/null)
value=$(cat /etc/gocollect/core.meta/osso-isms.yaml 2>/dev/null)

# Machines without a osso-isms.yaml won't get any OSSO-ISMS MOTD.
if test -z "$value"; then
    exit 0
fi

# HEADER
cat <<EOF

  +-------------[ ${WHITE}OSSO ISMS${NONE} ]--------------+
  |
EOF

# BODY
if test -z "$value"; then
    echo "  |  ${CYAN}This machine has no OSSO-ISMS config${NONE}"
else
    echo "$value" | sed -e '
      s/^/  | '${WHITE}'/
      s/$/'${NONE}'/
      s/\(level: high\)/'${RED}\\1${NONE}'/g
      s/\(level: medium\)/'${YELLOW}\\1${NONE}'/g
      s/\(level: low\)/'${GREEN}\\1${NONE}'/g
      s/\(level: [0-9]\)/'${GREEN}\\1${NONE}'/g
    '
fi

# FOOTER
cat <<EOF
  |
  +----------------------------------------+
EOF
